### ISSUE TITLE
Warning: Calling Resource#sha1 is deprecated!

### ISSUE THREAD

**Issue by zonuexe** [b4b4r07/homebrew-brionac#1]
```
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
Warning: Calling Hardware.is_64_bit? is deprecated!
Use Hardware::CPU.is_64_bit? instead.
/usr/local/Library/Taps/b4b4r07/homebrew-brionac/brionac.rb:7:in `<class:Brionac>'
Please report this to the b4b4r07/brionac tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/b4b4r07/homebrew-brionac/brionac.rb:9:in `<class:Brionac>'
Please report this to the b4b4r07/brionac tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/b4b4r07/homebrew-brionac/brionac.rb:9:in `<class:Brionac>'
Please report this to the b4b4r07/brionac tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/b4b4r07/homebrew-brionac/brionac.rb:9:in `<class:Brionac>'
Please report this to the b4b4r07/brionac tap!
```

**Comment by babarot** [comment]
Thank you for your reporting. I'll update the latest artifact and its sha1.
